spring:
  datasource:
    url: jdbc:mysql://localhost:3305/prueba
    username: alejo
    password: yahoocolombia1A
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    datasource-platfor: com.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
    generate-ddl: false

